name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu-latest:

    runs-on: ubuntu-latest
    container: ghcr.io/hyperk/hk-software:main
    steps:
    - name: Framework build
      run: cd /usr/local/hk/ToolFrameworkCore/src/ && sed -i 's!gray!grey!' src/Logging/Logging.h && make
    - name: build hk-datamodel
      run: git clone https://github.com/hyperk/hk-DataModel.git /usr/local/hk/hk-ToolApp/hk-DataModel && cd /usr/local/hk/hk-ToolApp/hk-DataModel && make  
    - uses: actions/checkout@v2
    - name: build WCSim
      run: |
        source /usr/local/hk/hk-pilot/setup.sh
        source /usr/local/hk/hk-software/install-Linux_x86_64-gcc_8-python_3.8.13/setup.sh
        source /usr/local/hk/ROOT/install-Linux_x86_64-gcc_8-python_3.8.13/bin/thisroot.sh
        source /usr/local/hk/Geant4/install-Linux_x86_64-gcc_8-python_3.8.13/bin/geant4.sh
        mkdir OriginalWCSim_build
        cd OriginalWCSim_build
        cmake ../OriginalWCSim
        make
        make install
    - name: build
      run: |
        source /usr/local/hk/hk-pilot/setup.sh
        source /usr/local/hk/hk-software/install-Linux_x86_64-gcc_8-python_3.8.13/setup.sh
        source /usr/local/hk/ROOT/install-Linux_x86_64-gcc_8-python_3.8.13/bin/thisroot.sh
        source /usr/local/hk/Geant4/install-Linux_x86_64-gcc_8-python_3.8.13/bin/geant4.sh
        mkdir -p /opt/hk-ToolApp/UserTools/ImportedTools/GHOST-WCSim/
        ls
        ln -s $PWD/OriginalWCSim_build/ /opt/hk-ToolApp/UserTools/ImportedTools/GHOST-WCSim/
        export WCSIMDIR=$PWD/OriginalWCSim/
        make
